### ISSUE TITLE
Shouldn't need "manage server" permissions to edit an event

### ISSUE THREAD

**Issue by EricScottN** [apollo-fyi/apollo-docs#16]
I would think it would be easy enough to do a [check](https://discordpy.readthedocs.io/en/stable/interactions/api.html?highlight=has_any_role#discord.app_commands.checks.has_any_role) for `discord.app_commands.checks.has_any_role(*items)` on the `/edit` slash command. Is there a reason I would have to give my mods "manage server" permissions to edit events? That requirement seems way too high and raises a security issue granting it to anybody but an admin.

**Comment by reiichi001** [comment]
Please post feedback / feature requests onto the appropriate site, <https://feedback.apollo.fyi/>.

This repository is only for Apollo's Documentation site, <https://docs.apollo.fyi/>

That said, the `/edit` command has two separate cases, and simply checking if the user can use the command or a role that allows the command is insufficient.

#### Use Case 1: A user uses `/edit` to edit their own event.
Apollo checks if the user who has pressed the [Edit] button or used `/edit` is the creator of that event. If so, they are allowed to modify it. Otherwise, it proceeds to the next case. A user needs no special permissions beyond being able to see the channel and use slash commands here.

#### Use Case 2: An administrative user uses `/edit` to edit someone else's event.
If the check for event creator failed, Apollo then checks if the user has "Manage Server" permissions, which it uses as its indicator of "this is an administrator and they should be allowed administrative functions." 

Because editing an event can let you cancel it, change all information/details, and add/remove user signups, this rightly requires an administrative check. It would be a security issue to just let any user modify any other user's events.

Furthermore, Apollo uses "Manage Server" permissions for several other administrative functions, mostly tied to the `/server` command, where one can edit server-wide settings such as auto_delete, purge, auto_delete times, the reminder interval, and for select commands, role grants/restrictions. (Ideally, `/edit` and /sort` would have a role grant option here, like the request for them here: <https://feedback.apollo.fyi/p/add-additional-apollo-based-role-checks>
